config/routes.rb
Rails.application.routes.draw do
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root 'courses#index'

	# courses
	get 'courses/new', to: 'courses#new'

	# pages
	get 'about', to: 'pages#about'

	# students
	resources :students, expect: [:destroy]

	# login
	get 'login', to: 'sessions#new'
	post 'login', to: 'sessions#create'
	delete 'logout', to: 'sessions#destroy'

	# student_courses
	post 'course_enroll', to: 'student_courses#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
    validates :name, presence: true, length: { minimun: 5, maximum: 50 }
    validates :short_name, presence: true, length: { minimun: 2, maximum: 5 }
    validates :description, presence: true

    has_many :student_courses
    has_many :students, through: :student_courses

end

app/models/student.rb
class Student < ApplicationRecord
    before_save { self.email = email.downcase }
    
    validates :name, presence: true
    
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 105 }, 
                uniqueness: { case_sensitive: false },
                format: { with: VALID_EMAIL_REGEX }

    has_secure_password

    has_many :student_courses
    has_many :courses, through: :student_courses
    
end

app/models/student_course.rb
class StudentCourse < ApplicationRecord
    belongs_to :student
    belongs_to :course
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :require_user

    helper_method :current_user, :logged_in?
    
    def current_user
        # memoizing instance variable; perform query only if current_student doesn't exist
        @current_student ||= Student.find(session[:student_id]) if session[:student_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:warning] = 'You must be logged in to perform that action'
            redirect_to login_path
        end
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
    skip_before_action :require_user, only: [:index]

    def index
        @courses = Course.all
    end

    def new
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    skip_before_action :require_user, only: [:about]

    def about
        
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_before_action :require_user, only: [:new, :create]

    def new
    end

    def create
        student = Student.find_by(email: params[:sessions][:email].downcase)
        if student && student.authenticate(params[:sessions][:password])
            session[:student_id]  = student.id
            flash[:success] = 'You have successfully logged in'
            redirect_to student_path(student)
        else
            flash.now[:danger] = 'Something was wrong with your login information'
            render 'new'
        end
    end

    def destroy
        session[:student_id] = nil
        flash[:warning] = 'You have successfully logged out'
        redirect_to root_path
    end
end

app/controllers/student_courses_controller.rb
class StudentCoursesController < ApplicationController
    def create
        course_to_add = Course.find(params[:course_id])
        unless current_user.courses.include?(course_to_add)
            StudentCourse.create(course: course_to_add, student: current_user)
            flash[:success] = "You have successfully enrolled in #{course_to_add.name}"
            redirect_to student_path(current_user)
        else
            flash[:danger] = 'Something went wrong with your enrollment'
            redirect_to root_path
        end
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    skip_before_action :require_user, only: [:new, :create]
    before_action :set_student, only: [:show, :edit, :update]
    before_action :require_same_student, only: [:edit, :update]

    def index
        @students = Student.all
    end

    def show
    end

    def new
        @student = Student.new
    end

    def create
        @student = Student.new(student_params)
        if @student.save
            flash[:success] = 'You have successfully signed up!'
            redirect_to students_path
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        if @student.update(student_params)
            flash[:success] = 'You have successfully updated you profile'
            redirect_to student_path(@student)
        else
            render 'edit'
        end
    end

    private

    def student_params
        params.require(:student).permit(:name, :email, :password, :password_confirmation)
    end

    def set_student
        @student = Student.find(params[:id])
    end

    def require_same_student
        if current_user != @student
            flash[:danger] = 'You can only edit your own profile'
            redirect_to student_path(current_user)
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def session_link
        if (!logged_in?)
            link_to('Log In', login_path, class: "dropdown-item")
        else
            link_to('Log Out', logout_path, method: :delete, class: "dropdown-item")
        end
    end
end

app/views/courses/index.html.erb
<!-- Heading Row -->
<div class="row align-items-center my-5">
    <div class="col-lg-7">
        <img class="img-fluid rounded mb-4 mb-lg-0" src="https://via.placeholder.com/900x400" alt="">
    </div>
    <!-- /.col-lg-8 -->
    <div class="col-lg-5">
        <h1 class="font-weight-light">Courses Listing</h1>
        <p>This is a template that is great for small businesses. It doesn't have too much fancy flare to it, but it makes a great use of the standard Bootstrap core components. Feel free to use this template for any project you want!</p>
        <a class="btn btn-primary" href="#">Call to Action!</a>
    </div>
    <!-- /.col-md-4 -->
</div>
<!-- /.row -->

<!-- Call to Action Well -->
<div class="card text-white bg-secondary my-5 py-4 text-center">
    <div class="card-body">
        <p class="text-white m-0">This call to action card is a great place to showcase some important information or display a clever tagline!</p>
    </div>
</div>

<!-- Content Row -->
<div class="row">
    <% @courses.each do |course| %>
        <div class="col-md-4 mb-5">
            <div class="card h-100">
                <div class="card-body">
                    <h2 class="card-title"><%= course.short_name %>: <%= course.name %></h2>
                    <p class="card-text"><%= course.description %></p>
                </div>
                <div class="card-footer">
                    <a href="#" class="btn btn-primary btn-sm">More Info</a>
                    <% if (logged_in?) && !(current_user.courses.include?(course)) %>
                        <%= link_to 'Enroll', course_enroll_path(course_id: course.id), method: :post, class: "btn btn-warning btn-sm" %>
                    <% end %>
                </div>
            </div>
        </div>
        <!-- /.col-md-4 -->
    <% end %>

</div>
<!-- /.row -->

app/views/courses/new.html.erb
<h2>courses new page</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Tech University</title>
		<%= csrf_meta_tags %>
		<%= csp_meta_tag %>

		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	</head>

	<body>

		<!-- Navigation -->
		<%= render 'partials/nav' %>
		
		<br>			
		<!-- Display flash messages -->
		<% flash.each do |key, msg| %>
			<%= content_tag :div, msg, class: "alert alert-#{key}", id: "fade-out-target" %>
		<% end %>		
	  
		<!-- Page Content -->
		<div class="container">
			<%= yield %>
		</div>
		<!-- /.container -->
	  
		<!-- Footer -->
		<%= render 'partials/footer' %>
	  
		<!-- Bootstrap core JavaScript -->
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
		
	</body>
</html>

app/views/pages/about.html.erb
<h2>pages about</h2>

app/views/partials/_footer.html.erb
<!-- Footer -->
<footer class="py-4 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019</p>
    </div>
    <!-- /.container -->
</footer>

app/views/partials/_nav.html.erb
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="/">HS University</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Courses
                        <span class="sr-only">(current)</span>
                    </a>
                    <%# link_to '<span class="sr-only">(current)</span>'.html_safe, 'Courses', root_path, class: "nav-link" %>
                </li>
                <% if (logged_in?) %>
                    <li class="nav-item">
                        <%= link_to 'Students', students_path, class: "nav-link" %>
                    </li>
                <% end %>
                
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Account
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <% if (logged_in? ) %>
                            <a><%= link_to 'My Profile', student_path(current_user), class: "dropdown-item" %></a>
                        <% end %>
                        <hr>
                        <a><%= session_link %></a>
                    </div>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="#">Contact</a>
                </li>
                <li class="nav-item">
                    <%= link_to 'About', about_path, class: "nav-link" %>
                </li>
            </ul>
        </div>
    </div>
</nav>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
    <div class="alert alert-warning" role="alert">
        <strong><%= pluralize(object.errors.count, "error") %></strong>
        prohibited your profile from being created!
    </div>

    <% object.errors.full_messages.each do |msg| %>
        <div class="alert alert-danger" role="alert">
            <%= msg %>
        </div>
    <% end %>
<% end %>

app/views/students/_form.html.erb
<!-- Heading Row -->
<div class="row align-items-center my-5">
    <div class="col-lg-7">
        <img class="img-fluid rounded mb-4 mb-lg-0" src="https://via.placeholder.com/900x400" alt="">
    </div>
    <!-- /.col-lg-8 -->
    <div class="col-lg-5">
        <h1 class="font-weight-light"><%= @student.new_record? ? 'Sign up future student' : 'Update your profile' %></h1>
        <p>This is a template that is great for small businesses. It doesn't have too much fancy flare to it, but it makes a great use of the standard Bootstrap core components. Feel free to use this template for any project you want!</p>
        <a class="btn btn-primary" href="#">Call to Action!</a>
        <%= link_to '<i class="icon"></i>Back'.html_safe, students_path, class: "btn btn-warning" %>
    </div>
    <!-- /.col-md-4 -->
</div>
<!-- /.row -->

<%= render 'shared/errors', object: @student %>

<%= form_for(@student, html: { class: "your-class-here" })  do |f| %>
    <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control", placeholder: "Enter name" %>
    </div>

    <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, class: "form-control", placeholder: " Enter email" %>
    </div>

    <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control", placeholder: " Enter password" %>
    </div>

    <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: "form-control", placeholder: " Confirm your password" %>
    </div>

    <%= f.submit(@student.new_record? ? 'Sign Up' : 'Update Profile', class: "btn btn-primary") %>
<% end %>

<br>

app/views/students/edit.html.erb
<%= render 'form' %>

app/views/students/index.html.erb
<!-- Heading Row -->
<div class="row align-items-center my-5">
    <div class="col-lg-7">
        <img class="img-fluid rounded mb-4 mb-lg-0" src="https://via.placeholder.com/900x400" alt="">
    </div>
    <!-- /.col-lg-8 -->
    <div class="col-lg-5">
        <h1 class="font-weight-light">Students Directory</h1>
        <p>This is a template that is great for small businesses. It doesn't have too much fancy flare to it, but it makes a great use of the standard Bootstrap core components. Feel free to use this template for any project you want!</p>
        <a class="btn btn-primary" href="#">Call to Action!</a>
    </div>
    <!-- /.col-md-4 -->
</div>
<!-- /.row -->

<!-- Call to Action Well -->
<div class="card text-white bg-secondary my-5 py-4 text-center">
    <div class="card-body">
        <p class="text-white m-0">This call to action card is a great place to showcase some important information or display a clever tagline!</p>
    </div>
</div>

<!-- Content Row -->
<div class="row">
    <% @students.each do |student| %>
        <div class="col-md-4 mb-5">
            <div class="card h-100">
                <div class="card-body">
                    <h2 class="card-title"><%= student.name %></h2>
                    <p class="card-text"><%= student.email %></p>
                </div>
                <div class="card-footer">
                    <%= link_to 'View Profile', student_path(student), class: "btn btn-info btn-sm" %>
                </div>
            </div>
        </div>
        <!-- /.col-md-4 -->
    <% end %>

</div>
<!-- /.row -->

app/views/students/new.html.erb
<%= render 'form' %>

app/views/students/show.html.erb
<!-- Heading Row -->
<div class="row align-items-center my-5">
    <div class="col-lg-7">
        <img class="img-fluid rounded mb-4 mb-lg-0" src="https://via.placeholder.com/900x400" alt="">
    </div>
    <!-- /.col-lg-8 -->
    <div class="col-lg-5">
        <h1 class="font-weight-light">Student Profile</h1>
        <p><strong>Name: </strong><%= @student.name %></p>
        <p><strong>Email: </strong><%= @student.email %></p>
        <p><strong>Enrollments: </strong> <%= @student.courses.count %></p>
        <% if (current_user == @student) %>
            <%= link_to '<i class="icon"></i>Edit your profile'.html_safe, edit_student_path(@student), class: "btn btn-info" %>
        <% end %>
    </div>
    <!-- /.col-md-4 -->
</div>
<!-- /.row -->

<% if @student.courses.empty? %>
<!-- Call to Action Well -->
<div class="card text-white bg-secondary my-5 py-2 text-center">
    <div class="card-body">
        <h3>You are not enrolled in any courses yet</h3>
    </div>
</div>

<% else %>
<!-- Call to Action Well -->
<div class="card text-white bg-secondary my-5 py-2 text-center">
    <div class="card-body">
        <h2 class="text-center">You are enrolled in <%= @student.courses.count %> course(s). Start learning</h2>
    </div>
</div>

<!-- Content Row -->
<div class="row">
    <% @student.courses.each do |course| %>
        <div class="col-md-4 mb-5">
            <div class="card h-100">
                <div class="card-body">
                    <h2 class="card-title"><%= course.name %></h2>
                    <p class="card-text"><%= course.short_name %></p>
                    <p class="card-text"><%= course.description %></p>
                </div>
                <div class="card-footer">
                    <a href="#" class="btn btn-primary btn-sm">More Info</a>
                    <%# link_to 'View Profile', course_path(course), class: "btn btn-info btn-sm" %>
                </div>
            </div>
        </div>
        <!-- /.col-md-4 -->
    <% end %>
<% end %>

</div>
<!-- /.row -->